package mocks

import (
	"github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
)

// Float64ObservableGauge is an autogenerated mock type for the `Float64ObservableGauge` interface.
type Float64ObservableGauge struct {
	embedded.Float64ObservableGauge
	metric.Float64Observable
	mock.Mock
}

// NewFloat64ObservableGauge creates a new mock instance of `Float64ObservableGauge`.
// It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFloat64ObservableGauge(t interface {
	mock.TestingT
	Cleanup(func())
}) *Float64ObservableGauge {
	m := new(Float64ObservableGauge)
	m.Test(t)

	t.Cleanup(func() {
		m.AssertExpectations(t)
	})

	return m
}
