package mocks

import (
	"github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
)

// Int64ObservableGauge is an autogenerated mock type for the `Int64ObservableGauge` interface.
type Int64ObservableGauge struct {
	embedded.Int64ObservableGauge
	metric.Int64Observable
	mock.Mock
}

// NewInt64ObservableGauge creates a new mock instance of `Int64ObservableGauge`.
// It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInt64ObservableGauge(t interface {
	mock.TestingT
	Cleanup(func())
}) *Int64ObservableGauge {
	m := new(Int64ObservableGauge)
	m.Test(t)

	t.Cleanup(func() {
		m.AssertExpectations(t)
	})

	return m
}
