package mocks

import (
	"github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
)

// Int64ObservableCounter is an autogenerated mock type for the `Int64ObservableCounter` interface.
type Int64ObservableCounter struct {
	embedded.Int64ObservableCounter
	metric.Int64Observable
	mock.Mock
}

// NewInt64ObservableCounter creates a new mock instance of `Int64ObservableCounter`.
// It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInt64ObservableCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Int64ObservableCounter {
	m := new(Int64ObservableCounter)
	m.Test(t)

	t.Cleanup(func() {
		m.AssertExpectations(t)
	})

	return m
}
