name: Deploy QA3

on:
  pull_request:
    types:
      - closed

jobs:
  on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR Merge
        run: |
          echo The PR was merged. Init deployment to QA3.
